# Use root/example as user/password credentials
version: '3.1'


# --innodb-buffer-pool-size=10000
services:

  db:
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: mydb
    volumes:
      - ./dockerData:/data
    ports: 
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 28080:8080
